apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-todo
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/mysql-todo-data
